import { App, PluginSettingTab } from "obsidian";
import type { SettingDefinitionItem, SettingGroupItem } from "obsidian";
import type GranolaSyncPlugin from "./main";
import type { GranolaAccount } from "./main";
import type { SyncTimeRange } from "./mcp-client";
import { DEFAULT_DURATION_STYLE, formatDuration } from "./template";
import type { DurationStyle } from "./template";

export type SyncFrequency = "manual" | "startup" | "1m" | "15m" | "30m" | "60m" | "12h";

export const SYNC_FREQUENCY_OPTIONS: Record<SyncFrequency, string> = {
	manual: "Manual only (command palette)",
	startup: "Sync on startup only",
	"1m": "Every 1 minute",
	"15m": "Every 15 minutes",
	"30m": "Every 30 minutes",
	"60m": "Every 60 minutes",
	"12h": "Every 12 hours",
};

export const SYNC_FREQUENCY_MS: Record<SyncFrequency, number | null> = {
	manual: null,
	startup: null,
	"1m": 60 * 1000,
	"15m": 15 * 60 * 1000,
	"30m": 30 * 60 * 1000,
	"60m": 60 * 60 * 1000,
	"12h": 12 * 60 * 60 * 1000,
};

const SYNC_TIME_RANGE_OPTIONS: Record<SyncTimeRange, string> = {
	this_week: "This week",
	last_week: "Last week",
	last_30_days: "Last 30 days",
};

/**
 * Label each duration style with what it actually produces, generated by the
 * same formatter the notes use rather than written out here.
 *
 * Unit names come from the reader's locale, so hard-coding English examples
 * would show a German user "1h 14m" in the dropdown and then write
 * "1 Std. 14 Min." into their notes. Built per render, since the locale can
 * change without the plugin reloading.
 */
function durationStyleOptions(): Record<DurationStyle, string> {
	const sample = 74;
	return {
		compact: `Compact (${formatDuration(sample, "compact")})`,
		long: `Long (${formatDuration(sample, "long")})`,
		minutes: `Minutes only (${formatDuration(sample, "minutes")})`,
	};
}

export interface GranolaSyncSettings {
	folderPath: string;
	filenamePattern: string;
	templatePath: string;
	syncFrequency: SyncFrequency;
	showRibbonIcon: boolean;
	skipExistingNotes: boolean;
	matchAttendeesByEmail: boolean;
	excludeSelfFromAttendees: boolean;
	syncTimeRange: SyncTimeRange;
	includeTranscripts: boolean;
	durationStyle: DurationStyle;
	granolaApiKey: string;
	onlyMyMeetings: boolean;
}

export const DEFAULT_SETTINGS: GranolaSyncSettings = {
	folderPath: "Meetings",
	filenamePattern: "{date} {title}",
	templatePath: "Templates/Granola.md",
	syncFrequency: "15m",
	showRibbonIcon: true,
	skipExistingNotes: true,
	matchAttendeesByEmail: true,
	excludeSelfFromAttendees: true,
	syncTimeRange: "last_30_days",
	includeTranscripts: false,
	durationStyle: DEFAULT_DURATION_STYLE,
	granolaApiKey: "",
	onlyMyMeetings: true,
};

type SettingKey = keyof GranolaSyncSettings;

export class GranolaSyncSettingTab extends PluginSettingTab {
	plugin: GranolaSyncPlugin;

	constructor(app: App, plugin: GranolaSyncPlugin) {
		super(app, plugin);
		this.plugin = plugin;
	}

	override getSettingDefinitions(): SettingDefinitionItem<SettingKey>[] {
		return [this.accountsList(), this.syncGroup(), this.notesGroup()];
	}

	/**
	 * Persist through the plugin rather than the inherited default, which writes
	 * `plugin.settings` straight to data.json — that file also carries the stored
	 * OAuth accounts, so a direct write would drop them and force a re-login.
	 * Settings whose value drives live state apply it here too.
	 */
	override async setControlValue(key: string, value: unknown): Promise<void> {
		Object.assign(this.plugin.settings, { [key]: value });
		await this.plugin.saveSettings();

		if (key === "syncFrequency") this.plugin.setupSyncInterval();
		if (key === "showRibbonIcon") this.plugin.updateRibbonIcon();
	}

	private accountsList(): SettingDefinitionItem<SettingKey> {
		const connected = this.plugin.accounts.filter((a) => a.oauthTokens !== undefined);

		return {
			type: "list",
			heading: "Granola accounts",
			addItem: {
				name: "Add Granola account",
				action: () => void this.plugin.addAccount(),
			},
			items:
				connected.length === 0
					? [this.connectPrompt()]
					: connected.map((account) => this.accountRow(account)),
		};
	}

	private connectPrompt(): SettingGroupItem<SettingKey> {
		return {
			name: "Not connected",
			desc: "Connect a Granola account to sync meetings via the official API.",
			aliases: ["sign in", "log in", "oauth"],
			render: (setting) => {
				setting.addButton((button) =>
					button
						.setButtonText("Connect to Granola")
						.setCta()
						.onClick(() => void this.plugin.addAccount())
				);
			},
		};
	}

	private accountRow(account: GranolaAccount): SettingGroupItem<SettingKey> {
		return {
			name: account.label || "Connected account",
			desc: account.needsReauth
				? "Reconnection required — your login expired. Sign in again to resume syncing."
				: account.label
					? "Connected and ready to sync."
					: "Connected. (Account name unavailable.)",
			// The row's name is the account label, so search needs the words a
			// user would actually type to find it.
			aliases: ["granola account", "disconnect", "reconnect", "sign out"],
			render: (setting) => {
				if (account.needsReauth) {
					setting.addButton((button) =>
						button
							.setButtonText("Reconnect")
							.setCta()
							.onClick(() => void this.plugin.reconnectAccount(account.id))
					);
				}

				setting.addButton((button) =>
					button
						.setButtonText("Disconnect")
						.setDestructive()
						.onClick(async () => {
							await this.plugin.disconnectAccount(account.id);
							this.update();
						})
				);
			},
		};
	}

	private syncGroup(): SettingDefinitionItem<SettingKey> {
		return {
			type: "group",
			heading: "Sync",
			items: [
				{
					name: "Sync now",
					desc: "Manually sync meetings from Granola",
					// A button rather than an `action` row: nothing marks a row as
					// clickable, and `action`'s row-index argument shows it is meant
					// for list entries, not a standalone command.
					render: (setting) => {
						setting.addButton((button) =>
							button
								.setButtonText("Sync now")
								.setCta()
								.onClick(() => void this.plugin.syncMeetings(true))
						);
					},
				},
				{
					name: "Time range",
					desc: "How far back to look for meetings when syncing",
					control: {
						type: "dropdown",
						key: "syncTimeRange",
						options: SYNC_TIME_RANGE_OPTIONS,
						defaultValue: DEFAULT_SETTINGS.syncTimeRange,
					},
				},
				{
					name: "Sync frequency",
					desc: "How often to automatically sync meetings from Granola",
					control: {
						type: "dropdown",
						key: "syncFrequency",
						options: SYNC_FREQUENCY_OPTIONS,
						defaultValue: DEFAULT_SETTINGS.syncFrequency,
					},
				},
				{
					name: "Only my meetings",
					desc: "Sync only meetings you recorded or were listed as a participant in, including notes shared with you. Disable to also sync every workspace-visible meeting.",
					control: {
						type: "toggle",
						key: "onlyMyMeetings",
						defaultValue: DEFAULT_SETTINGS.onlyMyMeetings,
					},
				},
			],
		};
	}

	private notesGroup(): SettingDefinitionItem<SettingKey> {
		return {
			type: "group",
			heading: "Notes",
			items: [
				{
					name: "Folder path",
					desc: "Where to save meeting notes. Takes date tokens, so Meetings/{date:YYYY/MM} files each meeting into a subfolder for its month.",
					// Plain text rather than a folder suggester: the value is a pattern,
					// and date tokens name folders that don't exist yet.
					control: {
						type: "text",
						key: "folderPath",
						placeholder: "Meetings",
						defaultValue: DEFAULT_SETTINGS.folderPath,
					},
				},
				{
					name: "Filename pattern",
					desc: "Pattern for note filenames. Available: {date}, {date:YYYY-MM-DD}, {title}, {id}",
					control: {
						type: "text",
						key: "filenamePattern",
						placeholder: "{date} {title}",
						defaultValue: DEFAULT_SETTINGS.filenamePattern,
						validate: (value) =>
							value.trim() ? undefined : "Enter a pattern — notes need a filename.",
					},
				},
				{
					name: "Template path",
					desc: "Path to template file in your vault. A default one is created when the plugin is first enabled.",
					// A picker, so it can only choose files that already exist — which
					// is why the plugin writes the default template on enable rather
					// than waiting for the first sync. To start a new template from
					// the default, duplicate that file in the vault and pick the copy.
					control: {
						type: "file",
						key: "templatePath",
						placeholder: DEFAULT_SETTINGS.templatePath,
						defaultValue: DEFAULT_SETTINGS.templatePath,
						filter: (file) => file.extension === "md",
					},
				},
				{
					name: "Show ribbon icon",
					desc: "Show a sync button in the left ribbon",
					control: {
						type: "toggle",
						key: "showRibbonIcon",
						defaultValue: DEFAULT_SETTINGS.showRibbonIcon,
					},
				},
				{
					name: "Skip existing notes",
					desc: "When enabled, existing notes won't be overwritten. Disable to update notes when Granola data changes. Existing notes are matched by `granola_id` anywhere in your vault, not just the sync folder.",
					control: {
						type: "toggle",
						key: "skipExistingNotes",
						defaultValue: DEFAULT_SETTINGS.skipExistingNotes,
					},
				},
				{
					name: "Granola API key",
					desc: "Optional. Fills in meeting length and end time, which the plugin cannot work out otherwise. Create one in the Granola desktop app under Settings > Connectors > API keys; it needs a Business or Enterprise plan. Obsidian stores plugin settings unencrypted inside your vault, so this key is saved in plain text and travels wherever your vault syncs.",
					control: {
						type: "text",
						key: "granolaApiKey",
						placeholder: "grn_…",
						defaultValue: DEFAULT_SETTINGS.granolaApiKey,
						validate: (value) =>
							!value.trim() || value.trim().startsWith("grn_")
								? undefined
								: "Granola API keys start with grn_.",
					},
				},
				{
					name: "Duration format",
					desc: "How meeting length is written by {{granola_duration_formatted}}. Unit names follow the language Obsidian is set to.",
					control: {
						type: "dropdown",
						key: "durationStyle",
						options: durationStyleOptions(),
						defaultValue: DEFAULT_SETTINGS.durationStyle,
					},
				},
				{
					name: "Include transcripts",
					desc: "Add the full meeting transcript to each note.",
					control: {
						type: "toggle",
						key: "includeTranscripts",
						defaultValue: DEFAULT_SETTINGS.includeTranscripts,
					},
				},
				{
					name: "Exclude yourself from attendees",
					desc: "Leave your own Granola account out of the attendee list, since you are listed on every meeting you take part in.",
					control: {
						type: "toggle",
						key: "excludeSelfFromAttendees",
						defaultValue: DEFAULT_SETTINGS.excludeSelfFromAttendees,
					},
				},
				{
					name: "Match attendees by email",
					desc: "Link attendees to existing notes that have a matching email in their 'emails' frontmatter property.",
					control: {
						type: "toggle",
						key: "matchAttendeesByEmail",
						defaultValue: DEFAULT_SETTINGS.matchAttendeesByEmail,
					},
				},
			],
		};
	}
}
